//
//  RefreshTokenInfoSheet.swift
//  BetterBlue
//
//  Explainer + confirmation sheet for switching a Hyundai Europe
//  account to refresh-token authentication. Shared by `AddAccountView`
//  (new accounts) and `AccountInfoView` (existing accounts) so the
//  copy stays consistent in both places — they both need to tell the
//  user what a refresh token is, point at the external generator, and
//  surface a clear "confirm switch" affordance with a cancel escape.
//

import SwiftUI

struct RefreshTokenInfoSheet: View {
    /// Fired when the user taps the bottom-bar confirm button.
    /// Callers handle the state mutation (flipping their `useToken`
    /// flag, focusing the new field, etc.) — this sheet only owns
    /// the explanation + intent capture, not the side effects.
    let onConfirm: () -> Void
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 16) {
                    Text("A refresh token is a long-lived key generated " +
                         "outside the app — it lasts months and survives " +
                         "signing in on multiple devices.")
                        .fixedSize(horizontal: false, vertical: true)

                    Text("Use this option if you're already signed in to " +
                         "Bluelink on other devices, or if you want to " +
                         "avoid sharing your password with BetterBlue.")
                        .fixedSize(horizontal: false, vertical: true)

                    if let attributed = try? AttributedString(
                        markdown: "Tokens aren't generated by BetterBlue " +
                            "directly. Follow the instructions at " +
                            "[bluelink-refresh-token]" +
                            "(https://github.com/TMA84/bluelink-refresh-token/blob/main/README.md) " +
                            "to produce one, then paste it into the " +
                            "Refresh Token field after confirming below."
                    ) {
                        Text(attributed)
                            .tint(.blue)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
                .font(.body)
                .foregroundStyle(.primary)
                .padding()
                .frame(maxWidth: .infinity, alignment: .leading)
            }
            .navigationTitle("Use Refresh Token")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button {
                        dismiss()
                    } label: {
                        Image(systemName: "xmark")
                    }
                    .accessibilityLabel("Cancel")
                }
                ToolbarItem(placement: .bottomBar) {
                    Button {
                        onConfirm()
                        dismiss()
                    } label: {
                        Text("Use Refresh Token")
                            .frame(maxWidth: .infinity)
                    }
                    .buttonStyle(.borderedProminent)
                    .controlSize(.large)
                }
            }
            .presentationDetents([.medium, .large])
        }
    }
}
